yarn.lock
=> Update d2-ui commit revision to point to current dataset-configuration

src/DataSets/FormSteps.component.js, src/DataSets/Forms/GeneralInformation.component.js, src/DataSets/Forms/InitialConfig.component.js, src/DataSets/Forms/OrganisationUnit.component.js, src/DataSets/Forms/Save.component.js, src/DataSets/Forms/Sections.component.js, src/forms/FormHelpers.js, src/forms/MultiSelect.component.js, src/i18n/i18n_module_ar.properties, src/i18n/i18n_module_en.properties, src/i18n/i18n_module_es.properties, src/i18n/i18n_module_fr.properties, src/models/DataSetStore.js, src/models/Section.js
Closes #18 
Also, I've moved model logic from FormSteps to DataSetStore.
=> Save dataset/sections + move model logic to DataSetStore

src/i18n/i18n_module_ar.properties, src/i18n/i18n_module_en.properties, src/i18n/i18n_module_es.properties, src/i18n/i18n_module_fr.properties
Closes #48 
(also, add last line-feed)
=> Add missing i18n/short_name

src/DataSets/FormSteps.component.js, src/Wizard/Wizard.component.js
Closes #54 
default: top, sections tabs: top/bottom
=> Configurable actions bar position

src/App/App.component.js, src/SessionDialog/SessionDialog.component.js, src/app.js, src/i18n/i18n_module_ar.properties, src/i18n/i18n_module_en.properties, src/i18n/i18n_module_es.properties, src/i18n/i18n_module_fr.properties, webpack.config.js
Closes #44 
Checks on app bootup and every 10 seconds.
=> Check server on app start and timed intervals

src/SessionDialog/SessionDialog.component.js, src/app.js, src/utils/Dhis2Helpers.js
=> Move redirectToLogin to dhis2 utils module

resources/customjscss/nrc.css
Closes #61
Path `resources/customjscss/nrc.css` (as it could be any other...)
=> Add custom CSS used by NRC

src/DataSets/Forms/Sharing.component.js, src/i18n/i18n_module_ar.properties, src/i18n/i18n_module_en.properties, src/i18n/i18n_module_es.properties, src/i18n/i18n_module_fr.properties
=> Sharing: Add help message for country selector

package.json, src/models/DataSetStore.js
=> Remove auto-bind library

src/DataSets/FormSteps.component.js, src/DataSets/Forms/Sections.component.js, src/i18n/i18n_module_ar.properties, src/i18n/i18n_module_en.properties, src/i18n/i18n_module_es.properties, src/i18n/i18n_module_fr.properties
=> Add filter by selected on sections

src/DataSets/Forms/InitialConfig.component.js, src/DataSets/Forms/Sections.component.js
=> Move group-dataelements option to sections popover

src/DataSets/Forms/Sharing.component.js
=> Fix countries sharing from step 3

src/DataSets/DataSets.component.js
=> Implement columns sorting in landing page

resources/customjscss/data-entry-contentscript.js
Closes #138
It works now with the 4 states of row/col totals. Code refactored to build the table from scratch, not modifying it in-place. This will make #137 way easier.
=> Show totals and refactor

src/models/Section.js
=> Set default selected data elements on sections added after component render

src/forms/GreyFieldsTable.component.js
=> Split tables to a maximum (10) columns on disaggregation

resources/customjscss/nrc.css
=> Set max-width on textareas to fix position

src/forms/GreyFieldsTable.component.js
Avoid react warning on console.
=> Add key to child table in disaggregation on split

src/DataSets/DataSets.component.js
=> Get specific fields on dataset list to reduce network usage

src/forms/DataSetElementCategoryComboSelectionDialog.component.js
=> Use span instead of div for disaggregation de text to avoid ghost hovering

src/DataSets/Forms/Save.component.js, src/DataSets/Forms/Sections.component.js, src/forms/DataSetElementCategoryComboSelectionDialog.component.js
=> Show orgUnits in save step

package.json, src/DataSets/Forms/OrganisationUnit.component.js, src/i18n/i18n_module_ar.properties, src/i18n/i18n_module_en.properties, src/i18n/i18n_module_es.properties, src/i18n/i18n_module_fr.properties, yarn.lock
Close #209 
(added module scroll-to-component, it may come handy in other places)
=> Show error message on orgUnit step if no units selected

src/DataSets/FormSteps.component.js
=> Show spinner on wizard initialization

src/models/Section.js
=> Only status=active items in sections can be preselected

resources/customjscss/data-entry-contentscript.js, resources/customjscss/nrc.css
Closes #216 
(uses jquery.el.focusin/focusout)
=> Highlight all focused data elements rows on dataentry

resources/customjscss/nrc.css
Closes #215 
Setting a max-width and allowing word breaks seems to look pretty good.
=> Custom Css: tweak column width and word wrapping

src/DataSets/Forms/Sections.component.js, src/models/DataSetStore.js
=> Consider sections step invalid if dataset has no sections

resources/customjscss/data-entry-contentscript.js
=> [dataentry customjs] Set data element description as title

src/DataSets/Forms/Sections.component.js, src/components/collapsible-box/CollapsibleBox.scss
=> Fix flex style of sections step

src/DataSets/Forms/Save.component.js, src/utils/Dhis2Helpers.js
Closes https://github.com/EyeSeeTea/dataset-configuration/issues/249
=> Limit orgUnits string on Save step

src/Settings/Settings.component.js, src/i18n/i18n_module_ar.properties, src/i18n/i18n_module_en.properties, src/i18n/i18n_module_es.properties, src/i18n/i18n_module_fr.properties, src/models/Section.js, src/models/Settings.js
=> Hide dataElements/indicators with HideInDataSet attribute set

package.json, resources/scripts/check-duplicate-group-sets-items.js, yarn.lock
Closes #254
Results with current dev.est database (93 items with duplicates):
```
dataElement[DI7UKFbInTC - CO-E12: # of childre] has duplicate references to sets: Status
dataElement[ON9xr2bfw9O - CO-E1-NFI: # of educ] has duplicate references to sets: Status
dataElement[fR5aa2SMz9G - CO-EO10D: # (sample)] has duplicate references to sets: Status
dataElement[wSBtwdDnk83 - CO-EO10N: # (sample)] has duplicate references to sets: Status
dataElement[cpB8mR2Tvw4 - CO-EO11D: # (sample)] has duplicate references to sets: Status
dataElement[TyFFfitcQiQ - CO-EO11N: # (sample)] has duplicate references to sets: Status
dataElement[JYcY9wE5hZW - CO-EO12D: # (sample)] has duplicate references to sets: Status
dataElement[ZfZ2IbxqF5f - CO-EO12N: # (sample)] has duplicate references to sets: Status …
```
=> Add scripts to check duplicate group set items

src/DataSets/Forms/Sections.component.js, src/i18n/i18n_module_ar.properties, src/i18n/i18n_module_en.properties, src/i18n/i18n_module_es.properties, src/i18n/i18n_module_fr.properties, src/models/Section.js
=> Show warning on sections step when many items are selected

src/DataSets/Forms/GeneralInformation.component.js
=> Hide period fields for non-admin user (#270)

src/App/App.component.js, src/DataSets/FormSteps.component.js, src/i18n/i18n_module_ar.properties, src/i18n/i18n_module_en.properties, src/i18n/i18n_module_es.properties, src/i18n/i18n_module_fr.properties, src/models/DataSetStore.js
Closes EyeSeeTea/dataset-configuration#268
=> Add header bar title and custom styles

src/DataSets/Forms/OrganisationUnit.component.js
Closes https://github.com/EyeSeeTea/dataset-configuration/issues/269
=> Display only area/facility on level filters

includes/feedback-tool/feedback-github.js, src/App/App.component.js, src/config/feedback.js
=> Fix/regenerate GitHub token 284

src/DataSets/Forms/Sections.component.js
=> Fix section selector text

src/models/DataSetStore.js
=> Append DataSet literal to project name when associated

src/forms/GreyFieldsTable.component.js, src/utils/Dhis2Helpers.js
=> Remove special category default on multicategory disaggregations

src/DataSets/Forms/InitialConfig.component.js, src/models/CustomForm.js, src/models/DataSetStore.js, src/models/Section.js, src/models/custom-form-resources/sectionForm.vm, src/utils/Dhis2Helpers.js
=> Improve locatization

src/DataSets/Forms/GeneralInformation.component.js
=> Remove periodType dropdown (app only implements monthly period)

src/Settings/Settings.component.js, src/i18n/i18n_module_ar.properties, src/i18n/i18n_module_en.properties, src/i18n/i18n_module_es.properties, src/i18n/i18n_module_fr.properties, src/models/DataSetStore.js, src/models/Settings.js
=> Set new attribute createByDataSetConfiguration to true on save

src/models/DataSetStore.js
Closes https://github.com/EyeSeeTea/user-app/issues/56 (this is a dataset-configuration issue)
=> Set openFuturePeriods field automatically

src/DataSets/DataSets.component.js, src/i18n/i18n_module_ar.properties, src/i18n/i18n_module_en.properties, src/i18n/i18n_module_es.properties, src/i18n/i18n_module_fr.properties, src/utils/Dhis2Helpers.js
Closes #330 
By default, checkbox is selected.
=> [landing page] Add a filter to shown only datasets created by app

includes/feedback-tool/feedback-dhis2.js
Closes https://github.com/EyeSeeTea/user-app/issues/59
=> Fetch translations with same-origin credentials to avoid 302

src/DataSets/DataSets.component.js, src/MultipleDataTable/MultipleDataTable.component.js
=> Create separate field for lastUpdated with human string

src/DataSets/Forms/GeneralInformation.component.js
This PR fixes a bug with the dataset.name uniqueness on edit mode.
=> Fix uniqueness on dataset edit

src/utils/Dhis2Helpers.js
We already had a truncating mechanism for the URL, but it started failing on the client before the 413 from the server, so let's be more restrictive. Also, order IDs by `lastUpdated:desc`, this way the oldest ones are the ones being discarded.
=> Refactor filterByApp truncating code

src/App/App.component.js, src/DataSets/Forms/GeneralInformation.component.js, src/DataSets/Forms/InitialConfig.component.js, src/MultipleDataTable/MultipleDataTableRow.component.js, src/forms/DataSetElementCategoryComboSelectionDialog.component.js, src/models/DataSetStore.js, src/models/custom-form-resources/script.js, src/models/dataset.js, src/utils/Dhis2Helpers.js, webpack.config.js
Closes #407 
Requires https://github.com/EyeSeeTea/d2-ui/pull/26
=> Feature/migration 2.31

src/models/DataSetStore.js
=> Fix start year for periods when apply flag enabled

src/DataSets/DataSetPeriods.js, src/DataSets/DataSets.component.js, src/DataSets/FormSteps.component.js, src/DataSets/PeriodsDialog.js, src/Settings/Settings.component.js, src/components/sharing-dialog/utils.js, src/forms/DataInputPeriods.component.js, src/forms/Dropdown.component.js, src/forms/GreyFieldsTable.component.js, src/forms/RichDropdown.component.js, src/forms/form-fields/drop-down.js, src/forms/form-fields/icon-picker.js, src/forms/form-fields/text-field.js, src/i18n/i18n_module_ar.properties, src/i18n/i18n_module_en.properties, src/i18n/i18n_module_es.properties, src/i18n/i18n_module_fr.properties, src/models/DataSetStore.js, src/models/Section.js, src/models/Settings.js, src/models/data-periods.js, src/utils/Dhis2Helpers.js
Closes https://app.clickup.com/t/1mmpkxt
- Use project start/end and output/outcome dates.
- Import `metadata/attributes.json` before using the fix.
Notes for the tester:
- Test single project save.
- Test bulk "set output/outcome period dates"
- Test with an existing data set (new attribute empty) and newly saved dataset (attribute not empty).
=> Fix data input periods 

src/scripts/migrate-datasets-input-periods.ts
Closes https://app.clickup.com/t/1nwuvje
=> Add migrate datasets script

src/DataSets/Forms/InitialConfig.component.js, src/DataSets/Forms/Save.component.js, src/i18n/i18n_module_ar.properties, src/i18n/i18n_module_en.properties, src/i18n/i18n_module_es.properties, src/i18n/i18n_module_fr.properties
Closes https://app.clickup.com/t/1mufewf
=> A3: Make the project field recommended in the first step [1mufewf]

src/models/DataSetStore.js
Needed by https://app.clickup.com/t/862kh7896
=> Remove core competencies and globalAdmin sharing

package.json, src/models/DataSetStore.js, src/models/dataset.js
Fixes https://app.clickup.com/t/8695f2011?comment=90120061408693&threadedComment=90120062327297
=> fix: Get categoryOption code (need for country matching)
