EyeSeeTea/dataset-configuration

src/forms/FormHelpers.js, src/forms/RichDropdown.component.js
Closes #62 
- Width set to 30%
- The icon was not clickable, now it is.
=> Reduce RichDropdown width and make icon clickable

src/DataSets/FormSteps.component.js, src/DataSets/Forms/Sections.component.js, src/DataSets/context.actions.js, src/MultipleDataTable/MultipleDataTableContextMenu.component.js, src/Snackbar/snack.actions.js, src/forms/DataSetElementCategoryComboSelectionDialog.component.js, src/models/DataSetStore.js, src/models/Section.js, src/router.js
Closes #114 
As we expected, the non-1:1 relationships with dhis2 entities (sections split, disaggregations being added instead of being set, etc) introduces some friction on the edit functionality. Surely you'll have some doubts when testing, we can check it together tomorrow.
=> Implement wizard edit

src/DataSets/DataSets.component.js, src/DataSets/list.actions.js
When opening a share/orgUnits dialog, then closing, then editing a dataset, then returning to the dataset list, the dialogs would pop up again.
=> Fix sharing/orgUnits actions

package.json, yarn.lock
Known vulnerabilities of older releases: CVE-2016-10707, CVE-2015-9251
=> Upgrade to jquery v3

src/DataSets/Forms/Sections.component.js, src/Settings/Settings.component.js, src/models/Settings.js
=> Validation message in step 4 is also displayed if user goes back

src/models/Section.js
=> Use indicator displayName instead of code as group title in custom form

src/models/DataSetStore.js
* **Issue:** Closes #346 
- Instead of using groups configured in feedback-tool, send the fatal save error message to the same groups than warning/success messages.
- Groups sent to: GL_GlobalAdministrator + [country]_M&EDatasetCompletion
- Docs updated: `On save, a notification will be sent to the group “GL_GlobalAdministrator” and, for each country, to the group [CountryCode] + “_M&EDatasetCompletion”. This notification will be sent on fatal error, warning or success.`
=> Change user group recipients to be notified on error/warning/success

src/DataSets/Forms/GeneralInformation.component.js, src/i18n/i18n_module_ar.properties, src/i18n/i18n_module_en.properties, src/i18n/i18n_module_es.properties, src/i18n/i18n_module_fr.properties
= PR. Pull request template
* **Issue:** Closes #369 
- FormBuilder bites again: we can force sync validations (like we do on render), but not async validations. Workaround: I added the async validations on the field (will be executed on focus out of the field), and also run the validations explicitly when the Next button is pressed. In this last case, the errors are shown above the component (like we do in other steps).
=> Add async validation for dataset name uniqueness

yarn.lock
* **Issue:** Related #365
- We use the github source for d2-ui, branch dataset-configuration. I updated to last version in yarn.lock.
1. There is a known bug with yarn, that old versions of gihub packages will be installed in node_modules. If you think this may be the case, clean the global cache and re-install: 
```
$ yarn cache clean
$ rm -rf node_modules/d2-ui 
$ yarn install --check-files
```
2. I had problems with sass in latest versions of node. If that happens to you, install a nodeenv with a 8.x version for example:  `nodeenv --node=8.15.1 ../env-8` and activate prior to installing or starting the server.
=> Update to latest d2-ui#dataset-configuration branch

src/models/custom-form-resources/sectionForm.vm
Fixes #383 
Add CSS class like we do in data elements.
Old:
With the fix:
=> [custom form] Add CSS for indicator name so the width is adjusted (like DEs)

package.json, src/DataSets/Forms/Disaggregation.component.js, src/forms/DataSetElementCategoryComboSelectionDialog.component.js, src/models/Section.js, src/models/custom-form-resources/script.js
Closes #381 
Implementation:
- Group dataElements from the the same indicator, exclude dataElement if its code ends with `-C` (comment). A change of disaggregation affects both.
- On search: Show full group (numerator and denominator, when grouped).
Notes:
On long data element names, we may have a line break because of the length and then another for the second dataelement. Maybe we can add a visual cue.
Filter:
=> [Disaggregation] Group non-comment data elements by indicator

package.json, yarn.lock
https://github.com/EyeSeeTea/dataset-configuration/network/alerts
I tried to fix the webpack-dev-server, but it forces to update 2 major webpack versions, which would require a lot of work to make it work. Since it's low serverity (dev server), I am ignoring it for now.
Some notes:
- I tried the automated fixes by github. Problems: you have to generate one PR for every security, it's better to have an independent way to do it. 
- Done using: `yarn why PACKAGE`  and yarn's [selective resolutions](https://yarnpkg.com/en/docs/selective-version-resolutions)
Let's see if those two alerts disappear after the merge.
=> [security] Update tar/fstream

src/models/Section.js, src/utils/Dhis2Helpers.js
Fix error "Section.js:526 Uncaught (in promise) TypeError: Cannot read property 'id' of undefined" due to `dataElement.dataElementGroups.toArray()` returning undefined values in the array. 
Now we use the `collectionToArray` wrapper for all this and other .toArray() accesses to avoid problems.
=> Use toArray wrapper to remove undefined values from d2 collection

src/models/DataSetStore.js
When a dataset was cloned, the `dataset.save` used the same custom form in DB instead of creating a new one. This fixes the problem.
=> Clear dataset.dataEntryForm to avoid the form being reused on d2 save

src/DataSets/DetailsBox.component.js, src/DataSets/Forms/Save.component.js, src/models/dataset.js
There were some uses of `project.name` and some of `project.displayName`. Let's use always `displayName`.
=> [fix] Use always project.displayName

src/DataSets/DataSetPeriods.js, src/DataSets/DataSets.component.js, src/DataSets/FormSteps.component.js, src/DataSets/PeriodsDialog.js, src/components/sharing-dialog/utils.js, src/forms/DataInputPeriods.component.js, src/forms/Dropdown.component.js, src/forms/GreyFieldsTable.component.js, src/forms/RichDropdown.component.js, src/forms/form-fields/drop-down.js, src/forms/form-fields/icon-picker.js, src/forms/form-fields/text-field.js, src/models/DataSetStore.js, src/models/Section.js, src/models/data-periods.js, src/utils/Dhis2Helpers.js
Closes https://app.clickup.com/t/1mmpkjn
The most relevant changes refer to sharing, as all access fields (externalAccess, publicAccess, userAccesses, userGroupAccesses) have been grouped into a new `sharing` property. Old properties can still be used, but must be explicitly requested. 
That change was introduced in 2.36 (undocumented, or at least I've been unable to find any reference on the release notes). Compare:
https://play.dhis2.org/2.35.8/api/dataSets/lyLU2wR22tC.json?fields=:owner
https://play.dhis2.org/2.36.4/api/dataSets/lyLU2wR22tC.json?fields=:owner
=> Migration to 2.36

package.json, src/DataSets/DataSets.component.js, src/app.js, src/models/Settings.js, src/utils/Dhis2Helpers.js
Closes https://app.clickup.com/t/1u62b16
- The function being refactored is `currentUserHasAdminRole(d2)`, with no access to `config`, so for now let's hardcode the group name. 
- currentUserIsSuperuser is checked only for settings (show UI button + initialize)
=> A user is an admin if belongs to GL_AllAdmins or has authority ALL

src/DataSets/context.actions.js
Related to https://app.clickup.com/t/1u62b16
Action "Change output/outcome end date for year" only shows dates for specific years, a UI section accessible only to admins. So we need to hide the contextual action unless the current user is an admin.
=> Show change-end-date-for-year contextual actions only for admins

src/DataSets/DataSets.component.js, src/models/DataSetStore.js
Closes https://app.clickup.com/t/865d6ft6f
To discuss: Do we need to create an script to change this second flag for existing data sets?
=> Change default values for createdByApp + sendNotification

src/models/DataSetStore.js
Closes https://app.clickup.com/t/865d6fte5
=> Use only country code (no core competency) for group sharings

package.json, src/models/DataSetStore.js, src/utils/Dhis2Helpers.js
Fixes https://app.clickup.com/t/862kh7896
- On save, category combos were retrieved with all their category option combos. That's a large response. Restrict the call to the category combos used in the data set being saved/created. The size is reduced drastically (example: 10.2k and 12 ms)
- Tested on edit and create.
=> [performance] Get only dataset category combos on save

package.json, src/models/Section.js
Closes https://app.clickup.com/t/8695f1ubf
=> Disable core items selection validation for all users

package.json, src/models/DataSetStore.js
Fixes https://app.clickup.com/t/8695f1yfq
Motivation: `d2.currentUser.getUserRoles` fails but the workaround uses `/api/users/ID`, an endpoint which has got extra protection on the last DHIS2 releases. So instead, let's call /api/me to get the user roles.
Tested: the user can edit existing data sets and create new ones.
=> Get current user roles using direct /api/me
